// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_platform_middleware from "./routes/(platform)/_middleware.ts";
import * as $_platform_favorite from "./routes/(platform)/favorite.ts";
import * as $_platform_greet from "./routes/(platform)/greet.tsx";
import * as $_platform_logout from "./routes/(platform)/logout.ts";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $character_id_ from "./routes/character/[id].tsx";
import * as $index from "./routes/index.tsx";
import * as $CharactersContainer from "./islands/CharactersContainer.tsx";
import * as $SearchBar from "./islands/SearchBar.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/(platform)/_middleware.ts": $_platform_middleware,
    "./routes/(platform)/favorite.ts": $_platform_favorite,
    "./routes/(platform)/greet.tsx": $_platform_greet,
    "./routes/(platform)/logout.ts": $_platform_logout,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/character/[id].tsx": $character_id_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/CharactersContainer.tsx": $CharactersContainer,
    "./islands/SearchBar.tsx": $SearchBar,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
